http:
  host: 127.0.0.1
  port: 3002
  # optional timeout configuration
  write-timeout: 10
  read-timeout: 10
  read-header-timeout: 10
  # optional tls configuration
  cert-path: "/tmp/cert.pem"
  key-path: "/tmp/key/key"
  ca-cert-path: "/tmp/cacert.pem"
  insecure-skip-verify: false
  client-auth-type: "RequireAndVerifyClientCert"
  # expose the configuration file on /config
  expose-configuration: false

# labels to add to the Prometheus metrics exposed by the HTTP server
labels:
  - category
  - owner
  - level

interval: 10

providers:
  # Static list of projects to check
  static:
    - name: "standards-insights"
      url: https://github.com/qonto/standards-insights.git
      branch: "main"
      path: "/tmp/projects/standards-insights"
      labels:
        team: sre
  # The ArgoCD provider will retrieve projects from ArgoCD and use the Spec.Source.RepoURL url to fetch the
  # projects. ArgoCD applications labels will automatically be added as labels to the project.
  argocd:
    url: "argocd-url"
    projects:
      - project-to-use
    selector: "app=foo"
    base-path: "/tmp/base"
    # Use ARGOCD_AUTH_TOKEN to pass the ArgoCD authentication token

# Optional Git configuration to clone the projects (pick one)
git:
  basic-auth:
    username: oauth2
    password: pass # You can use GIT_BASIC_AUTH_PASSWORD as well
  private-key:
    path: /home/mcorbin/.ssh/my_ssh_private_key
    password: key-password # you can use GIT_PRIVATE_KEY_PASSWORD







groups:
  - name: golang
    checks:
      - go-version-latest
      - go-main
    when:
      - golang-projects

checks:
  - name: go-version-latest
    labels:
      category: upgrade
      severity: critical
      owner: backend
    rules:
      - go-version-latest
  - name: go-main
    operator: and
    labels:
      category: misc
      severity: minor
      owner: backend
    rules:
      - go-main
      - go-version-latest
  - name: grep-test
    labels:
      category: misc
      severity: minor
      owner: backend
    rules:
      - grep-rule-fn

rules:
  - name: golang-projects
    files:
      - path: "go.mod"
        exists: true
  - name: go-version-latest
    files:
      - path: "go.mod"
        contains: "go 1.21"
  - name: go-main
    files:
      - path: "main.go"
        contains: "^(func main)"
  - name: grep-rule-fn
    grep:
      - path: "."
        recursive: true
        pattern: "NewGrepRule"
        match: true

  - name: allowed-projects
    project:
      - names: 
          - awesome-project1
          - awesome-project2
        match: true
  - name: excluded-projects
    project:
      - names: 
          - bad-project1
          - bad-project2
        match: false
  - name: matching-all-labels
    project:
      - labels: 
          team: backend
          language: golang
        match: true
  - name: excluding-all-labels
    project:
      - names: 
          team: backend
          language: golang
        match: false