http:
  host: 127.0.0.1
  port: 3002
  write-timeout: 10
  read-timeout: 10
  read-header-timeout: 10
  cert-path: "/tmp/cert.pem"
  key-path: "/tmp/key/key"
  ca-cert-path: "/tmp/cacert.pem"
  insecure-skip-verify: false
  client-auth-type: "RequireAndVerifyClientCert"

labels:
  - category
  - owner
  - level

interval: 10

providers:
  argocd:
    url: "https://todo.com"
  git: []

groups:
  - name: golang
    checks:
      - go-version-latest
      - go-main
    when:
      - golang-projects

checks:
  - name: go-version-latest
    labels:
      category: upgrade
      level: gold
      owner: backend
    rules:
      - go-version-latest
  - name: go-main
    labels:
      category: misc
      level: bronze
      owner: backend
    rules:
      - go-main

rules:
  - name: golang-projects
    files:
      - path: "go.mod"
        exists: true
  - name: go-version-latest
    files:
      - path: "go.mod"
        contains: "go 1.20"
  - name: go-main
    files:
      - path: "main.go"
        contains: "^(func main)"

