providers:
  argocd:
    url: "https://todo.com"
  git: []

groups:
  - name: golang
    checks:
      - go-version-latest
      - go-main
    rules:
      - golang-projects

checks:
  - name: go-version-latest
    category: upgrade
    level: gold
    owner: backend
    exclude: []
    include: []
    rules:
      - go-version-latest
  - name: go-main
    category: misc
    level: bronze
    owner: backend
    rules:
      - go-main

rules:
  - name: golang-projects
    files:
      - path: "go.mod"
        exists: true
  - name: go-version-latest
    files:
      - path: "go.mod"
        contains: "go 1.20"
  - name: go-main
    files:
      - path: "main.go"
        contains: "^(func main)"

