on:
  push:
    branches : [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: 1.21
      - uses: golangci/golangci-lint-action@v6
        with:
          version: v1.55.2
          args: --timeout=5m
          skip-cache: false
