on:
  push:
    branches : [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'
      - uses: golangci/golangci-lint-action@v3
        with:
          version: v1.64.2
          args: --timeout=5m
          skip-cache: false
